<?php

namespace App\Http\Requests\offers;

use Illuminate\Foundation\Http\FormRequest;

class CreateOfferval extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|max:100|unique:offers,name',
            'price' => 'required|numeric',
            'details' => 'required|'
        ];
    }

    public function messages()
    {
        return [
            'name.required' => __("messages.nameOfferRequire"),
            'name.unique' => __("messages.nameOfferUnique"),
            'price.numeric' => __("messages.priceOfferNumber"),
        ]; // TODO: Change the autogenerated stub
    }
}
